# Naive Bayes 실습

# 1. Gaussian Naive Bayes

- 데이터, 모듈 불러오기

In [2]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

C:\Users\kgh67\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
import pandas as pd

C:\Users\kgh67\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)

In [5]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [6]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [7]:
gnb = GaussianNB()
fitted = gnb.fit(iris.data, iris.target) #x와 y 다 넣기
y_pred=fitted.predict(iris.data)

In [8]:
fitted.predict_proba(iris.data)[[1,48,51,100]]

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [9]:
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

- Confusion matrix 구하기

In [10]:
from sklearn.metrics import confusion_matrix

C:\Users\kgh67\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [11]:
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

- Prior 설정하기

In [12]:
# 특정 범주의 확률을 바꿔줄 수 있다
gnb2 = GaussianNB(priors=[1/100,1/100,98/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]], dtype=int64)

In [14]:
gnb2 = GaussianNB(priors=[1/100,98/100,1/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]], dtype=int64)

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성

In [15]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
import numpy as np

In [17]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [18]:
X

array([[4, 2, 2, 1, 2, 2, 2, 1, 3, 2, 0, 2, 2, 1, 0, 2, 4, 3, 2, 1, 1, 4,
        1, 0, 3, 0, 3, 2, 2, 1, 1, 2, 3, 0, 0, 2, 0, 1, 1, 2, 2, 0, 4, 3,
        2, 0, 1, 2, 4, 3, 3, 2, 1, 3, 0, 0, 3, 4, 0, 1, 1, 0, 3, 0, 2, 3,
        4, 0, 0, 2, 3, 4, 2, 3, 2, 3, 2, 2, 3, 2, 1, 2, 0, 0, 1, 3, 2, 3,
        4, 3, 2, 0, 3, 3, 0, 1, 4, 3, 4, 1],
       [4, 3, 1, 1, 4, 1, 2, 1, 4, 4, 2, 2, 0, 3, 2, 3, 1, 0, 0, 2, 3, 1,
        4, 0, 4, 2, 1, 1, 3, 0, 2, 0, 3, 4, 2, 3, 0, 2, 1, 0, 4, 2, 2, 1,
        1, 0, 0, 2, 0, 0, 4, 1, 2, 2, 2, 2, 1, 0, 3, 2, 0, 3, 0, 3, 3, 2,
        4, 1, 3, 1, 4, 2, 4, 4, 1, 1, 3, 2, 4, 2, 0, 2, 3, 2, 1, 3, 0, 2,
        0, 0, 1, 4, 4, 1, 2, 4, 1, 0, 3, 2],
       [1, 2, 2, 3, 3, 4, 0, 0, 3, 0, 1, 0, 1, 2, 2, 1, 3, 2, 2, 4, 3, 2,
        3, 0, 0, 3, 4, 0, 4, 3, 1, 4, 0, 1, 0, 3, 0, 1, 1, 1, 1, 4, 1, 4,
        0, 3, 4, 2, 3, 2, 3, 4, 4, 2, 4, 1, 0, 0, 0, 0, 4, 1, 2, 0, 4, 0,
        4, 0, 1, 4, 1, 3, 3, 4, 1, 0, 1, 3, 1, 2, 4, 4, 4, 0, 3, 0, 4, 0,
        1, 2, 3, 3, 4,

In [19]:
y

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [20]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
print(clf.predict(X[2:3]))

[3]


In [22]:
clf.predict_proba(X[2:3])

array([[1.24625824e-33, 6.69015481e-37, 1.00000000e+00, 2.98544509e-35,
        3.77181601e-37, 1.94453994e-32]])

- prior 변경해보기

In [25]:
clf2 = MultinomialNB(class_prior=[0.1,0.1999,0.0001, 0.1,0.1,0.1])
clf2.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=[0.1, 0.1999, 0.0001, 0.1, 0.1, 0.1],
       fit_prior=True)

In [26]:
clf2.predict_proba(X[2:3])

array([[1.24625824e-30, 1.33736195e-33, 1.00000000e+00, 2.98544509e-32,
        3.77181601e-34, 1.94453994e-29]])

In [28]:
clf2.predict(X[2:3])

array([3])